### ISSUE TITLE
Images not loading for contacts. 

### ISSUE THREAD

**Issue by joannagoley** [vliz-be-opsci/bon-site-to-pages#7]

**Comment by kmexter** [comment]
In addition, we want the images to be a bit smaller: 1/3 smaller please?

**Comment by joannagoley** [comment]
Images still not loading

**Comment by kmexter** [comment]
and should be smaller (as I can see the space provided for them, that being too big)

**Comment by kmexter** [comment]
Images indeed are loading, but they are still look too large...reduce by 1/3?
